/*1*/
SELECT LASTNAME
FROM EMPLOYEESX;
/*2*/
SELECT DISTINCT LASTNAME FROM EMPLOYEESX;
/*3*/
SELECT *
FROM EMPLOYEESX 
WHERE LASTNAME = 'Smith';
/*4*/
SELECT *
FROM EMPLOYEESX 
WHERE LASTNAME = 'Smith' OR LASTNAME = 'Doe';
/*5*/
SELECT *
FROM EMPLOYEESX 
WHERE DEPARTMENT = 14;
/*6*/
SELECT *
FROM EMPLOYEESX 
WHERE DEPARTMENT = 37 OR DEPARTMENT = 77;
/*7*/
SELECT *
FROM EMPLOYEESX 
WHERE LASTNAME LIKE 'S%';
/*8*/
SELECT SUM(BUDGET), NAME
FROM DEPARTAMETSX
GROUP BY NAME;
/*9*/
SELECT COUNT(CODE), DEPARMENT
FROM EMPLOYEESX
GROUP BY DEPARTMENT;
/*10*/
SELECT *
FROM EMPLOYEESX E
JOIN DEPARTAMETSX D ON D.CODE = E.DEPARTMENT;
/*11*/
SELECT E.NAME, E.LASTNAME, D.NAME, D.BUDGET
FROM EMPLOYEESX E
JOIN DEPARTAMETSX D ON D.CODE = E.DEPARTMENT;
/*12*/
SELECT E.NAME, E.LASTNAME
FROM EMPLOYEESX E
JOIN DEPARTAMETSX D ON D.CODE = E.DEPARTMENT
WHERE D.BUDGET > 60000;
/*13*/
SELECT D.NAME, D.BUDGET
FROM DEPARTAMETSX D
WHERE D.BUDGET > (SELECT AVG(BUDGET) FROM DEPARTAMETSX);
/*14*/
SELECT COUNT(E.NAME) AS CUENTA, D.NAME
FROM EMPLOYEESX E
JOIN DEPARTAMETSX D ON E.DEPARTMENT = D.CODE
GROUP BY D.NAME
HAVING CUENTA > 2;