CREATE TABLE MANUFACTURERS(
    CODE INTEGER PRIMARY KEY,
    NAME_MAN VARCHAR2(50) NOT NULL
);

CREATE TABLE PRODUCTS(
    CODE INTEGER PRIMARY KEY,
    NAME_PRO VARCHAR2(50) NOT NULL,
    PRICE NUMBER(4) NOT NULL,
    MANUFACTURER INTEGER NOT NULL, 
    CONSTRAINT manufacturer_fk FOREIGN KEY (MANUFACTURER) REFERENCES MANUFACTURERS (CODE)
);