INSERT INTO STAFF 
(COD_EMP, NAME_EMPLOYEE, JOB, SALARY, COD_DEPT, COD_SUP)
VALUES
(0, 'pepe', 'director', 5000, 12, 0);

INSERT INTO STAFF 
(COD_EMP, NAME_EMPLOYEE, JOB, SALARY, COD_DEPT)
VALUES
(0998, 'Martínez', 'analyst', 5700, 05);

INSERT INTO STAFF 
(COD_EMP, NAME_EMPLOYEE, JOB, SALARY, COD_DEPT)
VALUES
(1004, 'Mulet', 'project manager', 7500, 10);

INSERT INTO STAFF 
(COD_EMP, NAME_EMPLOYEE, JOB, SALARY, COD_DEPT, COD_SUP)
VALUES
(1200, 'Muñoz', 'project manager', 3000, 10, 0413);

INSERT INTO STAFF 
(COD_EMP, NAME_EMPLOYEE, JOB, SALARY, COD_DEPT, COD_SUP)
VALUES
(1110, 'Ortiz', 'programmer', 4000, 08, 1008);