/*16. Select the name of each manufacturer along with the name and price of its
most expensive product. */

SELECT max(P.price) AS MAXIMO, P.MANUFACTURER AS MANU
FROM PRODUCTS P
GROUP BY P.MANUFACTURER
;

SELECT P.NAME_PRO, M.NAME_MAN
FROM PRODUCTS P
JOIN MANUFACTURERS M ON M.CODE = P.MANUFACTURER
WHERE P.PRICE IN (SELECT MAXIMO FROM(SELECT max(P.price) AS MAXIMO, P.MANUFACTURER AS MANU FROM PRODUCTS P GROUP BY P.MANUFACTURER))
;

SELECT M.NAME_MAN,
FROM (SELECT max(P.price) AS MAXIMO, P.MANUFACTURER AS MANU FROM PRODUCTS P GROUP BY P.MANUFACTURER)
JOIN MANUFACTURERS M ON M.CODE = MANU
JOIN PRODUCTS P ON M.CODE = 
;


SELECT *
FROM PRODUCTS;