SELECT P.NAME_PRO, M.NAME_MAN
FROM PRODUCTS P
JOIN MANUFACTURERS M ON M.CODE = P.MANUFACTURER
WHERE P.PRICE IN (SELECT MAXIMO FROM(SELECT max(P.price) AS MAXIMO, P.MANUFACTURER AS MANU FROM PRODUCTS P GROUP BY P.MANUFACTURER))
;