SELECT *
FROM PLAYERS P
WHERE P.NAME = "Pepe"
;
SELECT p.NAME, C.TEAM_NAME
FROM PLAYERS P
JOIN CLUBS c ON P.CLUB_ID = C.CLUB_ID
WHERE P.WEIGHT > 80
;
SELECT CA.DAY_ENCOUNTER, CA.FORAIGN_GOALS + CA.LOCAL_GOALS AS Goles_Totales
FROM CALENDARS CA
WHERE Goles_Totales > 10
;